#  課題3

## 要求事項
ロボット開発におけるご自身のスキルを示すプログラムを制作してください。 
ロボットそのものを扱うプログラムでなくとも、ロボットソフトウェア開発に通じるようなアルゴリズムに関するものや、実デバイスとの接続を意識したプログラムであるとより好ましいです。
既存の成果物を活用しても、新規に作成いただいても構いません。 

## 条件 / Requirements
* プログラムの目的・仕様・アピールポイントを説明する資料の添付
* 既存の成果物を提出する際に、チームで開発したものである場合はご自身が関与した部分を明らかにしてください

## 【注意事項 / Important Notes】
◎ 使用言語はC++ または Pythonであること +
◎ オブジェクト指向を意識した実装であること  +
◎ コードの保守性・可読性およびコメントも評価対象とします +
◎ AIツールの利用は可能ですが、提出いただいたコードについては後日の面接でご自身の言葉で説明していただきます +
◎ README には必ず以下を記載してください： +
　・ビルド方法・動作確認方法 +
　・プログラムの構成や背景（発想や狙い） +
　・工夫した点・アピールポイント +
　・AIツールを使用した場合、その内容と範囲  

## 【提出方法・期限 / Submission Method & Deadline】

・提出期限：本日より2週間以内 +
・提出形式：URL（Google Drive, GitHubなど） +
・ファイルにアクセス制限をかけないこと  


## プログラムの目的
組み込みシステムにおいては状態遷移システムをコアとしたシステム開発を行うことが多くある。 +
状態遷移システムを個別のシステムごとに開発を行うとコストや日程に影響が出るため、状態遷移システムを共通化することが望ましい。本プログラムでは、状態遷移システムを共通化するため遷移を行うエンジン部と状態を保持するステート部を分離し、ステート部の実装をユーザーが行うことで、状態遷移システムを共通化することを目的とする。

## 仕様
本システムの仕様は以下とする。 +
・状態遷移システムを共通化するため、状態遷移を行うエンジン部と状態を保持するステート部を分離する。 +
・エンジン部は状態遷移の管理を行い、ステート部は状態の保持と状態遷移の条件を定義する。 +
・ステート部の実装はユーザーが行うこととする。 +
・状態遷移の条件はユーザーが定義することとする。 +

## アピールポイント


## アーキテクチャ設計
### システム構成

[plantuml, state_machine, png]
----
@startuml

abstract TransitionInfo {
    #target: State
    #trigger: string

    +TransitionInfo(target: State, trigger: string)
    +{abstract}condition(): bool
}

abstract State {
    #name: string
    #parent: State
    #children: State[]
    #default_child_idx: int
    #transitions: TransitionInfo[]

    +State(name: string, parent: State, default_child: State)
    +add_transition(transition: TransitionInfo): void

    +{abstract}on_enter(): void
    +{abstract}on_exit(): void
    +{abstract}on_update(): void
}

class StateMachine {
    #states: State[]
    #current_active_state_idx_list: int[]
    #next_active_state_idx_list: int[]

    +add_state(state: State): void
    +update(): void
    -update_current_active_state_list(State: pivot_state): bool
    -looper(): void
}

State -- TransitionInfo
StateMachine -- State

@enduml
----
